---
title: 'Artificial life, complex systems and cloud computing: a short review'
author: "JJ Merelo"
date: "September 2nd, 2017"
output: 
  pdf_document: 
    keep_tex: true
bibliography: refs.bib
abstract:  "Cloud computing is the prevailing mode of designing, creating and deploying complex applications nowadays. Its underlying assumptions include distributed computing, but also new concepts that need to be incorporated in the different fields. In this short paper we will make a review of how the world of cloud computing has intersected the complex systems and artificial life field, and how it has been used as inspiration for new models or implementation of new and powerful algorithms"
---

## Introduction


[Cloud computing](https://en.wikipedia.org/wiki/Cloud_computing) is currently the dominant computing platform. Even if initially it was a metaphor applied to virtualized resources of any kind that could be accessed in a pay-per-use basis, it has extended itself way beyond its initial and simple translation of data center concepts to create completely new software architectures and methodologies for developing, testing and deploying large scale applications. 
These new methodologies have several key issues:

* Infrastructure is fully automatized and described by software; there is no *hard* boundary between software and hardware, which are developed at the same time, with an application accompanied by the description of the resources it needs. 

* Applications are a loose collection of resources which interact asynchronously, are independent of each other, and in many cases have their own vendors or product owners. Some resources are ephemeral, appearing when they are needed and vanishing afterwards, some are permanent, but all of them behave reactively, acting when they receive information, and asynchronously, never waiting for response to return but relying instead on promises or other programming language constructs.

* As such a collection, cloud-native applications become *organic*
  with parts of it changing without making the application as a whole a different one. There is internal evolution with continuous integration, testing and deployment, as well as evolution in the sense of a progress in fitness, as applications compete with others for mind and market share, as well as resources.

All these characteristics make the cloud an environment that is closer to artificial life than single or multidesktop applications. However, cloud computing is relatively new and, being as it is a techno-social system [@vespignani2009predicting,@JJ2016] it will probably constitute the object of study form the point of view of complex systems, although for the time being that has not been the case. That is the reason why we have decided to create this mini-review of how cloud computing has been applied in the alife/complex systems field, with an emphasis on those papers written in the last few years, when the cloud ecosystem has experimented a big diversity expansion, mainly due to the introduction of containers, isolated applications that act like lightweight virtual machines. We will do so in the next section.

## First steps towards cloud as complex systems

One of the most straightforward ways of connecting *old* algorithms to *new* technologies is simply to run those algorithms using a straightforward translation of the old technologies. Cloud computing, for instance, offers the possibility of instantiating computing nodes at a cost that is a fraction of buying them; thus it is just straightforward to port an on premises parallel implementation of whatever algorithm to a cloud-based one. That kind of transportation hardly deserves a paper, although it does present some challenges and has in fact been addressed in several ones; for instance [@Medel2017] studies how to create models of complex systems using cloud resources and [@merelo2011evostar] presents a system that uses free cloud storage services as a device for interchanging individuals in an evolutionary algorithm. Several other artificial life systems that use the cloud for storage are presented in a recent review [@taylor2016webal]; however, there are other ways of doing this kind of translation. One of the possibilities that cloud computing offers is the virtualization of computing resources and offering them *as a service*. For instance, offering robot evolution as a service [@du2017robot,@chen2010robot] so that anyone can work with without the need to set up their own infrastructure. Of course, these new implementations have their own scaling and scheduling issues which can be a challenge, but they are mostly a straightforward implementation of *x*-as-a-framework-or-implementation to *x*-as-a-service. Besides, as shown in the paper mentioned above, virtualizing contributes to a reduction of costs, which is one of the first-order results of working in the cloud, but still it is only a short step away from service-oriented architectures. 



This cloud-based setup does have the disadvantage of needing a permanent connection and possibly a high bandwidth. However, there is an interesting complex-systems approach to this: so-called *edge computing* [@satyanarayanan2017edge] moves cloud resources *close* to the service client via technologies that allow them to access other clients using peer to peer technologies, or using mesh networks or similar technologies to establish services that users of mainly mobile devices can access. Since these *edge* nodes kind of *surround* the user, they receive the denomination of *fog* computing too [@luan2015fog], which is studied mainly in the context of the Internet of Things. The devices and computing nodes constituting this *fog* are, effectively, a complex adaptive system [@yan2010application][@roca2018tackling]. However, the scale and sheer number of devices used in fog computing exceed by orders of magnitude the one in actual cloud computing system for the time being, so that for the time being these concepts are still not being applied to them. It is just, however, a matter of time and scale when cloud systems will be considered self-organizing and exhibit emergent behavior. We will refer to this in the next section.

## Complex cloud systems 

Complex cloud systems would make use of the underlying physical (or virtual) characteristics of the cloud to implement complex systems. Most cloud systems architectures are based on queues, which usually form the backbone of the whole system and are used to deliver information as well as activate different modules in a way that scales well. This feature is leveraged in [@bottone2016implementing], which implements an ant-based system using the MQTT queue management framework to deposit virtual pheromones, which are then *sniffed* by agents in an stigmergic algorithm. Instead of simply implementing an array in one of the virtual nodes or a database which can be read from any client, this is a way that translates bioinspired algorithms to their closest equivalent in a virtual environment, creating cloud native complex adaptive systems.

This can be taken further; every module in a cloud system is not adaptive, performing whatever service it has been programmed to do via its description. But lately, some cloud systems are being built with self-`*` principles in mind; as services in the cloud acquire autonomy in what is called *autonomic computing*, *adaptation* is not far away and services become adaptive, being able to self-organize and the whole system to self-heal, two agencies that make a cloud system acquire complex adaptive behaviour, such as being able to reconfigure connections, spawn new copies or eliminate them, all in an autonomic way without needing to rely on a central authority, using peer to peer protocols such as the *gossip* protocol [@LNCS44480129], which has actually been used for evolutionary algorithms [@laredo09cache] before cloud computing was even created. 

## Conclusions

As can be observed by the dearth of references for complex cloud systems or cloud-native artificial life, we are still in the early stages of its development, with the cloud being used mainly as a resource for the straightforward porting of earlier systems. Some steps have been taking in the realization of the complex adaptive nature of systems and in the application of complex systems methods such as stigmergy or gossip protocols to cloud native applications, but it is still an early stage of development. The next few months or years will undoubtedly bring new and unexpected developments to this field that will provide benefits in both directions: insights in the study of cloud as socio-technical systems and new ways of implementing cloud-native artificial life forms.

### Acknowledgements

This work has been supported in part by the Spanish Ministry of Economía y Competitividad, projects TIN2014-56494-C4-3-P (UGR-EPHEMECH).


## References
