---

- hosts: "{{target}}"
  sudo: yes
  tasks:
    - name: install prerrequisites
      command: apt-get update -y && apt-get upgrade -y
      command: apt-get install aptitude python-apt -y
    - name: install packages
      apt: pkg={{ item}}
      with_items:
        - git 
        - curl 
        - build-essential 
        - libssl-dev
        - nodejs
        - npm
    - name: Create links
      command: ln -s /usr/bin/nodejs /usr/bin/node
      ignore_errors: yes
    - name: Create profile
      copy: content="export PAPERTRAIL_PORT={{PAPERTRAIL_PORT}}; export PAPERTRAIL_HOST={{PAPERTRAIL_HOST}}" dest=/home/cloudy/.profile