FROM phusion/baseimage
MAINTAINER JJ Merelo "jjmerelo@gmail.com"
RUN echo "Building a docker environment for NodEO"
RUN apt-get update && apt-get upgrade -y
RUN apt-get iputils-ping
RUN apt-cache search nodejs
